### ISSUE TITLE
Some more examples

### ISSUE THREAD

**Issue by skprasadu** [jamesmacaulay/zelkova#4]
Just a suggestion, can you have some more examples. I am looking some examples from @ http://elm-lang.org/Examples.elm . This will be cool. 

I will also rewrite some of these, if I get some time.

Thanks
Krishna

**Comment by jamesmacaulay** [comment]
There are now two other examples, the demos from the Clojure/West talk, linked from the README:

* [Quil Flyer](http://jamesmacaulay.github.io/zelkova-quil-flyer/resources/public/index.html) ([source](https://github.com/jamesmacaulay/zelkova-quil-flyer))
* [Om Search](http://jamesmacaulay.github.io/zelkova-om-searcher/resources/public/index.html) ([source](https://github.com/jamesmacaulay/zelkova-om-searcher))
