### ISSUE TITLE
Mailing List :)

### ISSUE THREAD

**Issue by idibidiart** [jamesmacaulay/zelkova#6]
I was looking for a mailing list for Zelkova to contacting other enthusiasts about the possibility of talking about and demo-ing Zelkova at our next Reactive ClojureScript meetup (formerly, the SF Reagent Meetup http://www.meetup.com/Reactive-ClojureScript/ )

Any chance you could start a mailing list?

**Comment by jamesmacaulay** [comment]
[Here you go](https://groups.google.com/d/forum/zelkova-frp) :)

Also [added link to README](https://github.com/jamesmacaulay/zelkova/commit/5bd8c4f53c68f737feec77ec0bcdaa90e5bfe8a9).
